### ISSUE TITLE
Add some missed icons(First series)

### ISSUE THREAD

**Issue by Mosi2772** [worron/ACYLS#10]
distro : ubuntu gnome 16.04.2 LTS
version : latest version (ّI downloaded it again now)

Atom => Icon=atom ( https://atom.io/ )
Books => Icon=org.gnome.Books
Byobu => Icon=byobu
Calendar => Icon=org.gnome.Calendar
Color => Icon=preferences-color
Curlew => Icon=curlew
Documents => Icon=org.gnome.Documents
Kazam => Icon=kazam
plank => Icon=plank
Music => Icon=gnome-music

thank you for great icon theme :100:

**Comment by worron** [comment]
Ok, listed icons were added. Test it and report if something is missed.

**Comment by worron** [comment]
Seems like solved.
