### ISSUE TITLE
Space in file name causes cache generation to fail.

### ISSUE THREAD

**Issue by nezumisama** [worron/ACYLS#11]
The symlink `scalable/mimetypes/libreoffice3-oasis-text .svg` has a space in its name, causing cache generation to fail:
```
gtk-update-icon-cache -f .                
gtk-update-icon-cache: The generated cache was invalid.
```
Renaming the file to `libreoffice3-oasis-text.svg` fixes this issue.

**Comment by worron** [comment]
Thank you for this observation.
