### ISSUE TITLE
Create symlink for google chrome icon

### ISSUE THREAD

**Issue by meskarune** [worron/ACYLS#13]
There is an icon for chromium: chromium-browser.svg but not for google chrome browser. If possible you can symlink the chromium icon to google-chrome.png or the generic browser icon.

**Comment by worron** [comment]
Symlink 'google-chrome' already exist in this theme (`scalable/apps` directory).

**Comment by meskarune** [comment]
Oh, I see. For some reason the icon is not being used in my panel.

**Comment by worron** [comment]
You can check desktop file (usually located in `/usr/share/applications`) of your chrome installation. If icon name exact 'google-chrome' then it is some issue with panel/dock application.

**Comment by meskarune** [comment]
This is what I have in the .desktop file along with all the languages stuff:

```
StartupWMClass=Google-chrome
Exec=/usr/bin/google-chrome-stable %U
Terminal=false
Icon=google-chrome
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
Actions=NewWindow;NewPrivateWindow;
```

I'm really not sure what is going on.

**Comment by worron** [comment]
Since icon names exactly the same I'm afraid nothing can be done with icons theme.
