### ISSUE TITLE
file-roller

### ISSUE THREAD

**Issue by HanaO00** [worron/ACYLS#26]
Hello, when we right click a file, the icon for "create an archive" or when we right click on an archive, the "extract here" and "extract to" options, doesn't have the icons

**Comment by worron** [comment]
The ACYLS itself has the needed icons like `extract-archive`, `add-files-to-archive`. It's possible different icon names used in your system. Please provide exact icon names used in your system.

**Comment by HanaO00** [comment]
I do not know why that's it, where should I go to see the exact icon ?
I put you a capture, I take the opportunity to give other applications:
- qpdfview
- cherrytree
- adobe flash player
- xfce4-power-manager-settings
- qvidcap

**Comment by worron** [comment]
Added some recognized, but I need exact icon name for following applications
* adobe flash player
*  xfce4-power-manager-settings

To find application icon name check its desktop file (usually located in `/usr/share/applications`) 'Icon' option.

Unfortunately I can't propose reliable ricipe for context menu icon determination. Possibe you can aplly some theme where 'extract' icons present and check its content.

**Comment by HanaO00** [comment]
So there are some others missings icons : 
Icon=flash-player-properties
Icon=xfce4-power-manager-settings
Icon=emblem-mail
Icon=org.gnome.ArchiveManager

**Comment by worron** [comment]
Added missed icon and links. Icon `emblem-mail` already exist.

**Comment by HanaO00** [comment]
Oh sorry, didn't see this, so i don't know why but after updating the icon pack, some icons doesn't work,
I have another icons list : 
Icon=links_32x32.xpm
Icon=lxmusic
Icon=openbox
Icon=assistant-qt4
Icon=qt4logo
Icon=designer-qt4
Icon=linguist-qt4
Icon=qdbusviewer-qt4
Icon=assistant
Icon=QtProject-designer
Icon=linguist
Icon=qdbusviewer
Icon=xpad

Thank you

**Comment by worron** [comment]
Aside of icon there should be info (link to homepage or source code) about application itself. For example I have no clue what `assistant` icon for.

Anyway I'll try to add listed icons but that will take some time.
