### ISSUE TITLE
Additional icons

### ISSUE THREAD

**Issue by mattiadr** [worron/ACYLS#27]
Hi, is it possible to add these icons?

- [GRUB customizer](https://launchpad.net/grub-customizer)
- [IntelliJ IDEA](https://www.jetbrains.com/idea/)
- [qBittorrent](https://www.qbittorrent.org/)
- [Qalculate!](https://qalculate.github.io/)

Also `telegram-desktop` on arch linux uses a different icon name (`telegram`).

Thank You.

**Comment by worron** [comment]
No problem. Will do within a few days.

**Comment by mattiadr** [comment]
Icons are working thanks!
