### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by mattiadr** [worron/ACYLS#28]
Hi could you add these icons?

- [Discord](https://discordapp.com/)
- [Evince](https://en.wikipedia.org/wiki/Evince)
- [MEGA](https://mega.nz/sync)
- [Sublime Merge](https://www.sublimemerge.com/)

Thanks!

**Comment by worron** [comment]
The presentation for 'evince' icon [already exist](https://github.com/worron/ACYLS/blob/devel/scalable/apps/evince.svg) in the theme. Do you need another named link?

**Comment by mattiadr** [comment]
Ah, I didn't notice, apparently on arch the icon is named `org.gnome.Evince`.
Thanks for your work!

**Comment by mattiadr** [comment]
Also I just noticed that the MEGASync desktop file needs an icon called `mega`, not `megasync`.

**Comment by worron** [comment]
Ok, I've add mentioned names.

**Comment by mattiadr** [comment]
Thank you!
