### ISSUE TITLE
Illegal instruction on $ python3 ~/.icons/ACYLS/scripts/run.py

### ISSUE THREAD

**Issue by reubenlillie** [worron/ACYLS#7]
OS: [Bodhi Linux 4.0.0](http://www.bodhilinux.com/ "Bodhi Linux homepage")
Python3 = 3.5.2
pip=9.0.1
lxml=3.7.0

Thanks for your time.

**Comment by worron** [comment]
i have tried Bodhi live cd and I cannot reproduce the problem. Here is no enough information to make any suggestion.

Can you provide full error output?
Did you try run any other python scripts on your system?

**Comment by reubenlillie** [comment]
Thanks for trying the Bodhi live.
I had to install python3/lxml manually.
I'm sure I could have done something wrong.

Would you mind sharing the commands/processes you used to get python3/lxml to play nice with ACYLS?

**Comment by worron** [comment]
Still can't understand what exactly is the problem?

Anyway, here is how configuration script was launched on Live CD
```bash
$ sudo apt-get install git python3-lxml
$ git clone https://github.com/worron/ACYLS.git ~/.icons/ACYLS
$ python3 ~/.icons/ACYLS/scripts/run.py
```

**Comment by reubenlillie** [comment]
I'm not sure what I was doing wrong either, but it must have had something to do with the way I was configuring python3 when I was trying to match ACYLS dependencies.

I reconfigured the system by only installing the `phython3-lxml` package, and it works as expected.

Thanks for your help.
